version: "3.8"

services:
  db:
    image: mysql:8.0.23
    container_name: nextjs-cms
    restart: always
    environment:
      MYSQL_DATABASE: nextjs-cms
      MYSQL_ROOT_PASSWORD: test
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/postgresql/data/

  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080

volumes:
  db-data:
